import React from 'react';
import Link from 'next/link';

export const metadata = {
    title: 'ACES Study Material - Semester 4',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h1 className='head_text font-bold text-black text-4xl flex justify-center'>
                <div className='underline'>Semester 4</div>
            </h1>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'>Study Materials :</h2>
            <div className='grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3'>
                <ul>
                    <li> <Link href={"https://github.com/vivekkj123/ktu-s4-csl-202-digital-lab"}>Digital Lab (CSL202)</Link> </li>
                    <li> <Link href={"https://github.com/vivekkj123/ktu-s4-csl-204-os-lab"}>Operating Systems Lab (CSL204)</Link> </li>
                    <li> <Link href={"/studymaterial/S4/Notes/CST202"}>Computer Organisation And Architecture (CST202)</Link> </li>
                    <li> <Link href={"/studymaterial/S4/Notes/CST204"}>Database Management Systems (CST204)</Link> </li>
                    <li> <Link href={"/studymaterial/S4/Notes/CST206"}>Operating Systems (CST206)</Link> </li>
                    <li> <Link href={"/studymaterial/S4/Notes/EST200"}>Design And Engineering (EST200)</Link> </li>
                    <li> <Link href={"/studymaterial/S4/Notes/MAT206"}>Graph Theory (MAT206)</Link> </li>
                    <li> <Link href={"/studymaterial/S4/Notes/MCN202"}>Constitution Of India (MCN202)</Link> </li>
                </ul>       
            </div>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'>Previous Year Question Papers :</h2>
            <div className='grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3'>
                <ul>
                    <li> <Link href={"/studymaterial/S4/PreYearQuestion/CST202"}>Computer Organisation And Architecture (CST202)</Link> </li>
                    <li> <Link href={"/studymaterial/S4/PreYearQuestion/CST204"}>Database Management Systems (CST204)</Link> </li>
                    <li> <Link href={"/studymaterial/S4/PreYearQuestion/CST206"}>Operating Systems (CST206)</Link> </li>
                    <li> <Link href={"/studymaterial/S4/PreYearQuestion/EST200"}>Design And Engineering (EST200)</Link> </li>
                    <li> <Link href={"/studymaterial/S4/PreYearQuestion/MAT206"}>Graph Theory (MAT206)</Link> </li>
                    <li> <Link href={"/studymaterial/S4/PreYearQuestion/MCN202"}>Constitution Of India (MCN202)</Link> </li>
                </ul>       
            </div>
        </section>
    )
}

export default page