import React from 'react';
import Link from 'next/link';

export const metadata = {
    title: 'ACES Study Material - Semester 3 - Notes - Logic System Design',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h1 className='head_text font-bold text-black text-4xl flex sm:text-flex justify-center'>
                <Link href={"/studymaterial/S3"}><div className='underline'>Semester 3 : Notes : Logic System Design</div></Link>
            </h1>
            <div className=''>
                <h3 className='p-5 font-bold text-black text-xl'>Module 1:- Number systems, Operations & Codes</h3>
                <div className='ml-10'>
                    <div className='underline'>Syllabus<br/></div>
                    <ul className='ml-5 mb-5 list-disc'>
                        <li>Decimal, Binary, Octal and Hexadecimal Number Systems- Number Base Conversions</li>
                        <li>Addition, Subtraction, Multiplication and Division of binary numbers</li>
                        <li>Representation of negative numbers- Complements, Subtraction with complements</li>
                        <li>Addition and subtraction of BCD, Octal and Hexadecimal numbers</li>
                        <li>Binary codes- Decimal codes, Error detection codes, Reflected code, Character coding</li>
                        <li>Character coding schemes - ASCII, EBCDIC</li>
                    </ul>
                </div>
                <div className='flex items-center justify-center'>
                    <iframe src='https://drive.google.com/file/d/1EqSAXyQNKmtwCaFa4mrXeoe6LmBwQQQG/preview' height={480} allow="autoplay" className="w-full sm:w-2/3 lg:w-1/2"></iframe>
                </div>
            </div>
            <div className=''>
                <h3 className='p-5 font-bold text-black text-xl'>Module 2:- Boolean Algebra</h3>
                <div className='ml-10'>
                    <div className='underline'>Syllabus<br/></div>
                    <ul className='ml-5 mb-5 list-disc'>
                        <li>Postulates of Boolean Algebra</li>
                        <li>Basic theorems and Properties of Boolean Algebra</li>
                        <li>Boolean Functions - Canonical and Standard forms</li>
                        <li>Simplification of Boolean Functions- Using Karnaugh- Map Method (up to five variables), Don’t care conditions, product of sums simplification, Tabulation Method</li>
                        <li>Digital Logic Gates- Implementation of Boolean functions using basic and universal gates</li>
                    </ul>
                </div>
                <div className='flex items-center justify-center'>
                    <iframe src='https://drive.google.com/file/d/11TrVm4mFsWHc_VgUjUvEvgoLFDA0bnPY/preview' height={480} allow="autoplay" className="w-full sm:w-2/3 lg:w-1/2"></iframe>
                </div>
            </div>
            <div className=''>
                <h3 className='p-5 font-bold text-black text-xl'>Module 3:- Combinational Logic Circuits</h3>
                <div className='ml-10'>
                    <div className='underline'>Syllabus<br/></div>
                    <ul className='ml-5 mb-5 list-disc'>
                        <li>Design Procedure & Implementation of combinational logic circuits- Binary adders and subtractors, Binary Parallel adder, Carry look-ahead adder, BCD adder, Code converter, Magnitude Comparator, Decoder, Demultiplexer, Encoder, Multiplexer, Parity generator/ Checker</li>
                    </ul>
                </div>
                <div className='flex items-center justify-center'>
                    <iframe src='https://drive.google.com/file/d/1l_EjhBfwMDv47vemiOgI9YKJgvORT0nu/preview' height={480} allow="autoplay" className="w-full sm:w-2/3 lg:w-1/2"></iframe>
                </div>
            </div>
            <div className=''>
                <h3 className='p-5 font-bold text-black text-xl'>Module 4:- Sequential logic circuits</h3>
                <div className='ml-10'>
                    <div className='underline'>Syllabus<br/></div>
                    <ul className='ml-5 mb-5 list-disc'>
                        <li>Flip-flops - SR, JK, T and D</li>
                        <li>Triggering Of Flip-Flops - Master-Slave Flip-Flops, Edge-Triggered Flip-Flops</li>
                        <li>Excitation table and characteristic equation</li>
                        <li>Registers - Register with the parallel load</li>
                        <li>Counter Design: Asynchronous Counters - Binary and BCD counters, timing sequences and state diagrams</li>
                        <li>Synchronous Counters - Binary Up-down counter, BCD counter</li>
                    </ul>
                </div>
                <div className='flex items-center justify-center'>
                    <iframe src='https://drive.google.com/file/d/1YZ4yvOOMFXqrlkX7wZ0u2M-X7cxqPsER/preview' height={480} allow="autoplay" className="w-full sm:w-2/3 lg:w-1/2"></iframe>
                </div>
            </div>
            <div className=''>
                <h3 className='p-5 font-bold text-black text-xl'>Module 5:- Shift Registers & Arithmetic Algorithms</h3>
                <div className='ml-10'>
                    <div className='underline'>Syllabus<br/></div>
                    <ul className='ml-5 mb-5 list-disc'>
                        <li>Shift Registers - Serial In Serial Out, Serial In Parallel Out, Bidirectional Shift Register with Parallel load</li>
                        <li>Ring Counter, Johnson Counter - timing sequences and state diagrams</li>
                        <li>Algorithms for addition and subtraction of binary numbers in signed magnitude and 2's complement representations</li>
                        <li>Algorithm for addition and subtraction of BCD numbers</li>
                        <li>Representation of floating-point numbers, Algorithm for addition and subtraction of floating-point numbers</li>
                    </ul>
                </div>
                <div className='flex items-center justify-center'>
                    <iframe src='https://drive.google.com/file/d/11cuw_YCYpvRR8MbIEueJcGcRspr2_UpP/preview' height={480} allow="autoplay" className="w-full sm:w-2/3 lg:w-1/2"></iframe>
                </div>
            </div>
        </section>
    )
}

export default page