import React from 'react'

export const metadata = {
    title: 'ACES Study Material - Semester 3 - Notes - Data Structures',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h1 className='head_text font-bold text-black text-4xl flex justify-center'>
                <div className='underline'>Semester 3 : Notes : Data Structures</div>
            </h1>
            <div className=''>
                <h3 className='mt-5 head_text text-black text-xl'>Module 1:-</h3>
                <iframe src="https://drive.google.com/file/d/1-4FgFWnTaSnccBnAvGOQ7sucFDm023aF/preview" width="640" height="480" allow="autoplay" className='ml-5'></iframe>
            </div>
            <div>
                <h3 className='mt-5 head_text text-black text-xl'>Module 2:-</h3>
                <iframe src="https://drive.google.com/file/d/1GJgI57S8ZeSGKSP-Ttj2-OXcCHSJBhrt/preview" width="640" height="480" allow="autoplay" className='ml-5'></iframe>
            </div>
            <div>
                <h3 className='mt-5 head_text text-black text-xl'>Module 3:-</h3>
                <iframe src="https://drive.google.com/file/d/1-uSNZrW5xtX9xc1cY7mXqyAg3jjytH7c/preview" width="640" height="480" allow="autoplay" className='ml-5'></iframe>
            </div>
            <div>
                <h3 className='mt-5 head_text text-black text-xl'>Module 4:-</h3>
                <iframe src="https://drive.google.com/file/d/1qzgGr18BgoUT9O0ERAByCOZJQ2JRLyPX/preview" width="640" height="480" allow="autoplay" className='ml-5'></iframe>
            </div>
            <div>
                <h3 className='mt-5 head_text text-black text-xl'>Module 5:-</h3>
                <iframe src="https://drive.google.com/file/d/11XYA0F_KcarK5VbrqLP3VUw1sSPUACvb/preview" width="640" height="480" allow="autoplay" className='ml-5'></iframe>
            </div>
        </section>
    )
}

export default page