import TeamCard from '@components/team/teamcard'
import React from 'react'

export const metadata = {
    title: 'ACES Team',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'> Team : </h2>
            <div className="p-5 flex-center">
                <TeamCard />
            </div>
        </section>
    )
}

export default page