import ProjectCard from '@components/project/projectcard';
import React from 'react';

export const metadata = {
    title: 'ACES Student Projects',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'> Projects 🧑🏻‍💻 : </h2>
            <div className="">
                <ProjectCard />
            </div>
        </section>
    )
}

export default page