import Link from 'next/link'
import React from 'react'

export const metadata = {
    title: 'ACES Study Material - Semester 6 - Notes - Complier Design',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h1 className='head_text font-bold text-black text-4xl flex sm:text-flex justify-center'>
                <Link href={"/studymaterial/S3"}><div className='underline'>Semester 6 : Notes : Compiler Design</div></Link>
            </h1>
            <div className=''>
                <h3 className='p-5 font-bold text-black text-xl'>Module 1:- Introduction To Compilers and Lexical Analysis</h3>
                <div className='ml-10'>
                    Syllabus<br/>
                    <ul className='ml-5 mb-5 list-disc'>
                        <li>Analysis and synthesis phases, Phases of a compiler, Compiler writing tools, Bootstrapping  </li>
                        <li>Analysis of the source program, Analysis and synthesis phases, Phases of a compiler, Lexical Analysis, Role of Lexical Analyser, Input Buffering, Specification of Tokens, Recognition of Tokens.</li>
                    </ul>
                </div>
                <div className='flex items-center justify-center'>
                    <iframe src="https://drive.google.com/file/d/1-4FgFWnTaSnccBnAvGOQ7sucFDm023aF/preview" height={480} allow="autoplay" className="w-full sm:w-2/3 lg:w-1/2"></iframe>
                </div>
            </div>
            <div>
                <h3 className='p-5 font-bold text-black text-xl'>Module 2:- Introduction to Syntax Analysis</h3>
                <div className='ml-10'>
                    Syllabus<br/>
                    <ul className='ml-5 mb-5 list-disc'>
                        <li> </li>
                    </ul>
                </div>
                <div className='flex items-center justify-center'>
                    <iframe src="https://drive.google.com/file/d/1GJgI57S8ZeSGKSP-Ttj2-OXcCHSJBhrt/preview" height={480} allow="autoplay" className="w-full sm:w-2/3 lg:w-1/2"></iframe>
                </div>
            </div>
            <div>
                <h3 className='p-5 font-bold text-black text-xl'>Module 3:- </h3>
                <div className='ml-10'>
                    Syllabus<br/>
                    <ul className='ml-5 mb-5 list-disc'>
                        <li> </li>
                    </ul>
                </div>
                <div className='flex items-center justify-center'>
                    <iframe src="https://drive.google.com/file/d/1GJgI57S8ZeSGKSP-Ttj2-OXcCHSJBhrt/preview" height={480} allow="autoplay" className="w-full sm:w-2/3 lg:w-1/2"></iframe>
                </div>
            </div>
            <div>
                <h3 className='p-5 font-bold text-black text-xl'>Module 4:- </h3>
                <div className='ml-10'>
                    Syllabus<br/>
                    <ul className='ml-5 mb-5 list-disc'>
                        <li> </li>
                    </ul>
                </div>
                <div className='flex items-center justify-center'>
                    <iframe src="https://drive.google.com/file/d/1GJgI57S8ZeSGKSP-Ttj2-OXcCHSJBhrt/preview" height={480} allow="autoplay" className="w-full sm:w-2/3 lg:w-1/2"></iframe>
                </div>
            </div>
            <div>
                <h3 className='p-5 font-bold text-black text-xl'>Module 5:- </h3>
                <div className='ml-10'>
                    Syllabus<br/>
                    <ul className='ml-5 mb-5 list-disc'>
                        <li> </li>
                    </ul>
                </div>
                <div className='flex items-center justify-center'>
                    <iframe src="https://drive.google.com/file/d/1GJgI57S8ZeSGKSP-Ttj2-OXcCHSJBhrt/preview" height={480} allow="autoplay" className="w-full sm:w-2/3 lg:w-1/2"></iframe>
                </div>
            </div>
        </section>
    )
}

export default page