import React from 'react';
import Link from 'next/link';

export const metadata = {
    title: 'ACES Study Material - Semester 2',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h1 className='head_text font-bold text-black text-4xl flex justify-center'>
                <div className='underline'>Semester 2</div>
            </h1>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'>Study Materials :</h2>
            <div className='grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3'>
                <ul className="list-disc ml-5 w-full">
                    <li> <Link href={"/studymaterial/S2/Notes/CYT100"}>Engineering Chemistry (CYT100)</Link> </li>
                    <li> <Link href={"/studymaterial/S2/Notes/EST100"}>Engineering Mechanics (EST100)</Link> </li>
                    <li> <Link href={"/studymaterial/S2/Notes/EST102"}>Programming In C (EST102)</Link> </li>
                    <li> <Link href={"/studymaterial/S2/Notes/EST130"}>Basics Of Electrical And Electronics Engineering (EST130)</Link> </li>
                    <li> <Link href={"/studymaterial/S2/Notes/HUN102"}>Professional Communication (HUN102)</Link> </li>
                    <li> <Link href={"/studymaterial/S2/Notes/MAT102"}>Vector Calculus, Differential Equations And Transforms (MAT102)</Link> </li>
                </ul>       
            </div>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'>Previous Year Question Papers :</h2>
            <div className='grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3'>
                <ul className="list-disc ml-5 w-full">
                    <li> <Link href={"/studymaterial/S2/PreYearQuestion/CYT100"}>Engineering Chemistry (CYT100)</Link> </li>
                    <li> <Link href={"/studymaterial/S2/PreYearQuestion/EST100"}>Engineering Mechanics (EST100)</Link> </li>
                    <li> <Link href={"/studymaterial/S2/PreYearQuestion/EST102"}>Programming In C (EST102)</Link> </li>
                    <li> <Link href={"/studymaterial/S2/PreYearQuestion/EST130"}>Basics Of Electrical And Electronics Engineering (EST130)</Link> </li>
                    <li> <Link href={"/studymaterial/S2/PreYearQuestion/HUN102"}>Professional Communication (HUN102)</Link> </li>
                    <li> <Link href={"/studymaterial/S2/PreYearQuestion/MAT102"}>Vector Calculus, Differential Equations And Transforms (MAT102)</Link> </li>
                </ul>       
            </div>
        </section>
    )
}

export default page