"use client";

import Footer from '@components/footer';
import Navbar from '@components/navbar'
import '@styles/globals.css'
import { useState } from 'react'


const metadata = {
    title: 'ACES',
    description: 'Generated by Rahul A B',
}

export default function RootLayout({ children }) {
    const [darkMode, setDarkMode] = useState(false);
    
    const toggleDarkMode = () => {
        setDarkMode(!darkMode)
    };
    
    return (
        <html lang="en">
            <body className={`main-layout ${darkMode ? 'dark-mode' : ''}`}>
                <section className="min-h-screen">
                    <Navbar toggleDarkMode={toggleDarkMode} darkMode={darkMode} className='px-5' />
                    <div style={{ paddingTop: '80px'}} className='px-10'>{children}</div>
                    <Footer />
                </section>
            </body>
        </html>
    )
}