import Navbar from '@components/navbar'
import '@styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'ACES',
    description: 'Generated by Rahul A B',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <section className="min-h-screen">
                    <Navbar />
                    <div className='px-7'>{children}</div>
                </section>
            </body>
        </html>
    )
}