import React from 'react';
import Image from 'next/image';
import Gallery from '@components/gallary/gallery';
import EventCard from '@components/eventcard/eventcard';
import LogoCard from '@components/logocard/logocard';

export const metadata = {
    title: 'ACES Homepage',
    description: 'Generated by Rahul A B',
}

const Home = () => {
    return (
        <section className='w-full flex-col'>
            <div className='maintext'>
                <h1 className='head_text text-center'>
                    ACES Association    
                    <br/>
                    <span></span>
                </h1>
                <div className='flex-center'>
                    <p className='desc text-center'>
                        Department Of Computer Science And Engineering <br/>
                        Sahrdaya College Of Engineering & Technology, Kodakara
                    </p>
                </div>
            </div>
            <div>
                <h2 className='mt-5 font-bold text-black text-2xl'> Event Highlights: </h2>
                <Gallery />
            </div>
            <div>
                <h2 className='mt-5 font-bold text-black text-2xl'> Upcoming Events: </h2>
                <div className='flex-center py-6'>
                    <EventCard />
                </div>        
            </div>
            <div>
                <h2 className='mt-5 font-bold text-black text-2xl'> Group: </h2>
                <LogoCard />
            </div>
        </section>
    )
}

export default Home;