import React from 'react';
import Widget from '@components/widget';

export const metadata = {
    title: 'ACES Study Material',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'> Study Materials : </h2>
            <div className='flex'>
                <Widget type={"12"} />          
                <Widget type={"3"} />          
                <Widget type={"4"} />          
                <Widget type={"5"} />          
            </div>
        </section>
    )
}

export default page