import FacultyCard from '@components/facultycard'
import React from 'react'

export const metadata = {
    title: 'ACES Faculty',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'> Faculty : </h2>
            <div className="p-5">
                <FacultyCard className="flex" />
            </div>
        </section>
    )
}

export default page