import React from 'react'

export const metadata = {
    title: 'ACES Study Material - Semester 1',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h1 className='head_text font-bold text-black text-4xl flex justify-center'>
                <div className='underline'>Semester 1 : Notes : Engineering Graphics</div>
            </h1>
            <h3 className='mt-5 head_text font-bold text-black text-2xl'>Module 1 :-</h3>
            <h3 className='mt-5 head_text font-bold text-black text-2xl'>Module 2 :-</h3>
            <h3 className='mt-5 head_text font-bold text-black text-2xl'>Module 3 :-</h3>
            <h3 className='mt-5 head_text font-bold text-black text-2xl'>Module 4 :-</h3>
            <h3 className='mt-5 head_text font-bold text-black text-2xl'>Module 5 :-</h3>
        </section>
    )
}

export default page