import React from 'react';
import Link from 'next/link';

export const metadata = {
    title: 'ACES Study Material - Semester 6',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h1 className='head_text font-bold text-black text-4xl flex justify-center'>
                <div className='underline'>Semester 6</div>
            </h1>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'>Study Materials :</h2>
            <div className='grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3'>
                <ul>
                    <li> <Link href={"/studymaterial/S6/Notes/"}></Link> </li>
                </ul>       
            </div>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'>Previous Year Question Papers :</h2>
            <div className='grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3'>
                <ul>
                    <li> <Link href={"/studymaterial/S6/PreYearQuestion/"}></Link> </li>
                </ul>       
            </div>
        </section>
    )
}

export default page