import React from 'react';
import Link from 'next/link';

export const metadata = {
    title: 'ACES Study Material - Semester 6',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h1 className='head_text font-bold text-black text-4xl flex justify-center'>
                <div className='underline'>Semester 6</div>
            </h1>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'>Study Materials :</h2>
            <div className='grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3'>
                <ul className="list-disc ml-5 w-full">
                    <li> Networking Lab (CSL332) </li>
                    <li> <Link href={"/studymaterial/S6/Notes/CST302"}> Compiler Design (CST 302) </Link> </li>
                    <li> <Link href={"/studymaterial/S6/Notes/CST304"}> Computer Graphics And Image Processing (CST304) </Link> </li>
                    <li> <Link href={"/studymaterial/S6/Notes/CST306"}> Algorithm Analysis And Design (CST306) </Link> </li>
                    <li> <Link href={"/studymaterial/S6/Notes/CST308"}> Comprehensive Course Work (CST308) </Link> </li>
                    <li> <Link href={"/studymaterial/S6/Notes/CST322"}> Data Analytics (CST322) </Link> </li>
                    <li> <Link href={"/studymaterial/S6/Notes/HUT300"}> Industrial Economics And Foreign Trade (HUT300) </Link> </li>
                </ul>       
            </div>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'>Previous Year Question Papers :</h2>
            <div className='grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3'>
                <ul className="list-disc ml-5 w-full">
                    <li> <Link href={"/studymaterial/S6/PreYearQuestion/CST302"}> Compiler Design (CST 302) </Link> </li>
                    <li> <Link href={"/studymaterial/S6/PreYearQuestion/CST304"}> Computer Graphics And Image Processing (CST304) </Link> </li>
                    <li> <Link href={"/studymaterial/S6/PreYearQuestion/CST306"}> Algorithm Analysis And Design (CST306) </Link> </li>
                    <li> <Link href={"/studymaterial/S6/PreYearQuestion/CST308"}> Comprehensive Course Work (CST308) </Link> </li>
                    <li> <Link href={"/studymaterial/S6/PreYearQuestion/CST322"}> Data Analytics (CST322) </Link> </li>
                    <li> <Link href={"/studymaterial/S6/PreYearQuestion/HUT300"}> Industrial Economics And Foreign Trade (HUT300) </Link> </li>

                </ul>       
            </div>
        </section>
    )
}

export default page