import Link from 'next/link';
import React from 'react';
 

export const metadata = {
    title: 'ACES Study Material',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'> Study Materials : Semester 6 </h2>
            <div className="">
                <ul>
                    <li> </li>
                </ul>
            </div>
        </section>
    )
}

export default page