import Link from 'next/link'
import React from 'react'

export const metadata = {
    title: 'ACES Study Material - Semester 3 - Notes - Data Structures',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h1 className='head_text font-bold text-black text-4xl flex justify-center'>
                <Link href={"/studymaterial/S3"}><div className='underline'>Semester 3 : Notes : Data Structures</div></Link>
            </h1>
            <div className=''>
                <h3 className='p-5 font-bold text-black text-xl'>Module 1:- Basic Concepts of Data Structures</h3>
                <div className='ml-10'>
                    Syllabus<br/>
                    <ul className='ml-5 mb-5'>
                        <li>System Life Cycle, Algorithms, Performance Analysis, Space Complexity, Time Complexity</li>
                        <li>Asymptotic Notation, Complexity Calculation of Simple Algorithm</li>
                    </ul>
                    <iframe src="https://drive.google.com/file/d/1-4FgFWnTaSnccBnAvGOQ7sucFDm023aF/preview" width="640" height="480" allow="autoplay"></iframe>
                </div>
            </div>
            <div>
                <h3 className='p-5 font-bold text-black text-xl'>Module 2:- Arrays and Searching</h3>
                <div className='ml-10'>
                    Syllabus<br/>
                    <ul className='ml-5 mb-5'>
                        <li>Polynomial representation using Arrays, Sparse matrix, Stacks</li>
                        <li>Queues-Circular Queues, Priority Queues, Double-Ended Queues</li>
                        <li>Evaluation of Expressions Linear Search and Binary Search</li>
                    </ul>
                    <iframe src="https://drive.google.com/file/d/1GJgI57S8ZeSGKSP-Ttj2-OXcCHSJBhrt/preview" width="640" height="480" allow="autoplay"></iframe>
                </div>
            </div>
            <div>
                <h3 className='p-5 font-bold text-black text-xl'>Module 3:- Linked List and Memory Management</h3>
                <div className='ml-10'>
                    Syllabus<br/>
                    <ul className='ml-5 mb-5'>
                        <li>Self Referential Structures, Dynamic Memory Allocation, Singly Linked List-Operations on Linked List</li>
                        <li>Doubly Linked List, Circular Linked List, Stacks and Queues using Linked List</li>
                        <li>Polynomial representation using Linked List Memory allocation and de-allocation-First-fit, Best-fit and Worst-fit allocation schemes</li>
                    </ul>
                    <iframe src="https://drive.google.com/file/d/1-uSNZrW5xtX9xc1cY7mXqyAg3jjytH7c/preview" width="640" height="480" allow="autoplay"></iframe>
                </div>
            </div>
            <div>
                <h3 className='p-5 font-bold text-black text-xl'>Module 4:- Trees and Graphs</h3>
                <div className='ml-10'>
                    Syllabus<br/>
                    <ul className='ml-5 mb-5'>
                        <li>Trees, Binary Trees - Tree Operations, Binary Tree Representation, Tree Traversals</li>
                        <li>Binary Search Trees- Binary Search Tree Operations Graphs, Representation of Graphs</li>
                        <li>Depth First Search and Breadth-First Search on Graphs, Applications of Graphs</li>
                    </ul>
                    <iframe src="https://drive.google.com/file/d/1qzgGr18BgoUT9O0ERAByCOZJQ2JRLyPX/preview" width="640" height="480" allow="autoplay"></iframe>
                </div>
            </div>
            <div>
                <h3 className='p-5 font-bold text-black text-xl'>Module 5:- Sorting and Hashing</h3>
                <div className='ml-10'>
                    Syllabus<br/>
                    <ul className='ml-5 mb-5'>
                        <li>Sorting Techniques - Selection Sort, Insertion Sort, Quick Sort, Merge Sort and Heap Sort</li>
                        <li>Hashing - Hashing Techniques, Collision Resolution, Overflow handling</li>
                        <li>Hashing functions - Mid square, Division, Folding, Digit Analysis</li>
                    </ul>
                    <iframe src="https://drive.google.com/file/d/11XYA0F_KcarK5VbrqLP3VUw1sSPUACvb/preview" width="640" height="480" allow="autoplay"></iframe>
                </div>
            </div>
        </section>
    )
}

export default page