import React from 'react';
import Link from 'next/link';

export const metadata = {
    title: 'ACES Study Material - Semester 5',
    description: 'Generated by Rahul A B',
}

const page = () => {
    return (
        <section className='w-full flex-col'>
            <h1 className='head_text font-bold text-black text-4xl flex justify-center'>
                <div className='underline'>Semester 5</div>
            </h1>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'>Study Materials :</h2>
            <div className='grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3'>
                <ul className="list-disc ml-5 w-full">
                    <li> <Link href={"https://github.com/vivekkj123/ktu-s5-csl-331-ssmp-lab"}>System Software And Microprocessors Lab (CSL331)</Link> </li>
                    <li> <Link href={"https://github.com/vivekkj123/ktu-s5-csl-333-dbms-lab"}>Database Management Systems Lab (CSL333)</Link> </li>
                    <li> <Link href={"/studymaterial/S5/Notes/CST301"}>Formal Languages And Automata Theory (CST301)</Link> </li>
                    <li> <Link href={"/studymaterial/S5/Notes/CST303"}>Computer Networks (CST303)</Link> </li>
                    <li> <Link href={"/studymaterial/S5/Notes/CST305"}>Software Engineering (CST305)</Link> </li>
                    <li> <Link href={"/studymaterial/S5/Notes/CST307"}>Microprocessors And Microcontrollers (CST307)</Link> </li>
                    <li> <Link href={"/studymaterial/S5/Notes/CST309"}>Management Of Software Systems (CST309)</Link> </li>
                    <li> <Link href={"/studymaterial/S5/Notes/MCN301"}>Disaster Management (MCN301)</Link> </li>
                </ul>       
            </div>
            <h2 className='mt-5 head_text font-bold text-black text-2xl'>Previous Year Question Papers :</h2>
            <div className='grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3'>
                <ul className="list-disc ml-5 w-full">
                    <li> <Link href={"/studymaterial/S5/PreYearQuestion/CST301"}>Formal Languages And Automata Theory (CST301)</Link> </li>
                    <li> <Link href={"/studymaterial/S5/PreYearQuestion/CST303"}>Computer Networks (CST303)</Link> </li>
                    <li> <Link href={"/studymaterial/S5/PreYearQuestion/CST305"}>Software Engineering (CST305)</Link> </li>
                    <li> <Link href={"/studymaterial/S5/PreYearQuestion/CST307"}>Microprocessors And Microcontrollers (CST307)</Link> </li>
                    <li> <Link href={"/studymaterial/S5/PreYearQuestion/CST309"}>Management Of Software Systems (CST309)</Link> </li>
                    <li> <Link href={"/studymaterial/S5/PreYearQuestion/MCN301"}>Disaster Management (MCN301)</Link> </li>
                </ul>       
            </div>
        </section>
    )
}

export default page